Add functioning SPI communication and protocol
KMM2019-CrazyTaxi/sensor-module pull request #15
Opened 2019-11-21 15:50 UTC by angloth

# SPI protocol and structure

* Adds SPI init transmission code to the project
* Adds the interrupt based SPI communication protocol with the centralmodule that has been verified to work using dummy data.

## Relevant issues
Fixes #4 

## Testing
Dummy data was sent over the SPI buss to the centralmodule which was verified to be correct.

## Assignees
@Gravenstein to review

2019-11-23 18:39 UTC, Gravenstein commented on sensor_module/sensor_module/src/ASF/common/boards/user_board/init.c
> +	PORTA = 0xFF;
"Spårutskrifter" borde tas bort om koden är felsökt och klar.

2019-11-23 18:41 UTC, Gravenstein commented on sensor_module/sensor_module/src/src/spi.c
> +}
Får man några statuskoder från SPI? I så fall tror jag att det är en god idé att spara dem på något sätt, förslagsvis returnera statuskoden och spara den mottagna datan mha en pekare till funktionen. Det lär underlätta felsökning om vi får problem med kommunikationen i framtiden.

2019-11-23 18:41 UTC, Gravenstein commented on sensor_module/sensor_module/src/src/main.c
> +	PORTA = 0x02;
Ta bort spårutskrift

2019-11-23 18:42 UTC, Gravenstein commented on sensor_module/sensor_module/src/src/intercomm.c
> +	PORTA = check_byte;
Ta bort spårutskrift

2019-11-23 18:44 UTC, Gravenstein commented on sensor_module/sensor_module/src/src/intercomm.c
> +uint8_t check_byte = 0;
Måste dessa ligga som globala variabler? Kan de inte vara lokala borde de vara static, så att de endast är tillgängliga i denna fil.

2019-11-23 18:46 UTC, Gravenstein requested changes
Jag har gjort några småkommentarer som saker. Ang. felhanteringen kan vi kanske diskutera det imorgon.

2019-11-24 10:17 UTC, angloth commented
Some changes have been made and a new review is requested @Gravenstein

2019-11-24 10:49 UTC, Gravenstein approved these changes
Ser bra ut!

2019-11-24 10:49 UTC, merged